### ISSUE TITLE
My account - layout tweaks

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#390] opened 2014-12-06 18:09 UTC
Could there be a gap between the columns on the right hand side (apologies, may be a repeat request)

Not sure why column headings are red but text below is black.

![image](https://cloud.githubusercontent.com/assets/6060985/5328404/ed7ca81c-7d72-11e4-9492-d45777479bc9.png)

Could there be an explanation as to what the text is "I like fish". Not sure what the layout would look like if the profile info was far greater.

**Comment by pmackay** [comment] 2015-01-15 21:12
Duplicate of #420.

**Closed by pmackay** 2015-01-15 21:12 UTC
Labels: theming

**Comment by djwesto** [comment] 2015-01-15 23:19
I didn't realise that there was some profile description text that might appear in that left column there, @pmackay. Is that a sneaky booby trap you've set for me? What other fields have we never seen appear on the user profile page? I guess I'd better go and set up a profile with every single field filled out so we can check what actually appears on those profile pages...
