### ISSUE TITLE
Error selecting a venue

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#508] opened 2015-02-24 11:03 UTC
hernehill.org.

I was editing a draft of an event. Wanted to add a venue. Selected the "add venue" button. Got the page of all venues available, selected Brockwell Park, then  "submit" button and got an error message:

![image](https://cloud.githubusercontent.com/assets/6060985/6348018/923ece68-bc14-11e4-89e9-32b8cf9da8eb.png)

Also, not quite sure why there is a "select all" button for venues to be added to an event. Would be a fun event but is it needed? Bit of a distraction?

**Comment by pmackay** [comment] 2015-02-26 12:04
Would you want multiple selection at all? Or just choose one item?

**Comment by GilesGibson** [comment] 2015-02-26 12:10
But select all would od just that - select maybe a hundred venues in one go.I think being able to select more than one venue would be good - if there was a late night shopping evening then being able to select a dozen shops would be helpful.

**Comment by pmackay** [comment] 2015-02-26 12:54
Cannot reproduce on http://dev-openlocal.pantheon.io/, which has a bunch of software updates. Closing for now, can reopen if needed.

**Closed by pmackay** 2015-02-26 12:54 UTC
Labels: bug, p2 - desirable
