### ISSUE TITLE
News items wrapping on front page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#646] opened 2015-04-15 12:24 UTC
new site

![image](https://cloud.githubusercontent.com/assets/6060985/7158483/8f371e48-e372-11e4-9de2-f789ddc08faf.png)

The Crystal Palace News item is wrapping to a line below compared to the others.

**Comment by pmackay** [comment] 2015-04-15 12:29
Duplicate of #487. Please do check for existing issues.

**Closed as completed by pmackay** 2015-04-15 12:29 UTC
Labels: drupal-ui
