### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#682] opened 2016-01-12 11:44 UTC
Had two support issues over the last two days. Both users had problems logging in, kept on saying their password combo was wrong. I reset one password, am chasing up on the other issue. Strange that on one day we get two different users both with login issues. Anything changed?

**Comment by pmackay** [comment] 2016-01-12 11:46
Nothing has changed that I know of.

**Comment by GilesGibson** [comment] 2016-01-12 11:54
OK, I'll see how it goes.

**Comment by GilesGibson** [comment] 2016-02-04 17:05
We are still getting support issues about people unable to get past the change password link. The site still says that they get the password/login name wrong even after using the password reset link. Be good to know if the module that does this has any updates.

**Comment by GilesGibson** [comment] 2016-02-04 20:41
A typical support conversation that happens:

When it told me that to change my password to reset it I had to enter my old password the one I can't remember!

On Thu, Feb 4, 2016 at 8:14 PM, Giles Gibson giles@originaltg.com wrote:
So what happened when the site sent you the password reset email with the link in? Where did that grind to a halt?

From: Poppy Hasted poppy.hasted@gmail.com
Date: Thursday, 4 February 2016 at 20:00

To: Giles Gibson giles@originaltg.com
Subject: Re: Replacement login information for PoppyH at Herne Hill

It keeps telling me I can't change the password unless I enter the old password which is the bit I can't remember and is the reason why I want to xhange it!

On Thu, Feb 4, 2016 at 4:42 PM, Giles Gibson giles@originaltg.com wrote:
Yes of course it is OK to post and ad, not an issue. 

Chrome has the fear of opening a tab in incognito, that may work. 

If the site sent you a password reset then you got your email address correct and the link should then allow a one-time login. You should then immediately change your password again. Your username will then be displayed.

Let us know if still stuck.

Giles

From: Poppy Hasted poppy.hasted@gmail.com
Date: Thursday, 4 February 2016 at 16:39
To: Giles Gibson giles@originaltg.com
Subject: Re: Replacement login information for PoppyH at Herne Hill

I use a chromebook that automatically uses chrome. I know I'm alredy registered, i just can't remember what I usd as a user name and password...

What I want to do is post and ad for a carer/Personl Assistant. Would that be OK?

On Thu, Feb 4, 2016 at 4:35 PM, Giles Gibson giles@originaltg.com wrote:
Ouch, not much fun.

We do sometimes get problems with some browsers and sometimes the web site throws a sulk. 

If you had the patience could you try via another browser or use Incognito (Chrome) or similar web browser feature that does not use any of the existing cookies that have been set.

Thanks

Giles

From: Poppy Hasted poppy.hasted@gmail.com
Date: Thursday, 4 February 2016 at 16:27
To: Herne Hill info@hernehill.org.uk
Subject: Re: Replacement login information for PoppyH at Herne Hill

I am failing miserably to log in. It keeps telling me my password is invalid or unknown. HELP!

On Thu, Feb 4, 2016 at 4:18 PM, Herne Hill info@hernehill.org.uk wrote:
PoppyH,

A request to reset the password for your account has been made at Herne Hill.

You may now log in by clicking this link or copying and pasting it to your
browser:

http://www.hernehill.org.uk/user/reset/9493/1454602699/6k2iq1bXKVCt-awOZm2XMVlHTPXWSzZdz70AaNbrt5c

This link can only be used once to log in and will lead you to a page where
you can set your password. It expires after one day and nothing will happen
if it's not used.

--  Herne Hill team

**Comment by pmackay** [comment] 2017-01-31 11:45
Closing as cannot reproduce. Need to monitor.

**Closed as completed by pmackay** 2017-01-31 11:45 UTC
Labels: question, drupal, p3-low, openlocal-1
